package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.ExecBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Up'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Up")) {
    params {
        add {
            password("env.SENTRY_DSN", "credentialsJSON:205daec2-7af9-46f4-a515-9c9a90e027d0", display = ParameterDisplay.HIDDEN)
        }
        add {
            password("env.POSTGRES_CONNECTION_STRING", "credentialsJSON:58c6cb26-2f44-4165-affa-9e1496a59a09", display = ParameterDisplay.HIDDEN)
        }
        add {
            password("env.JWT_SECRET_KEY", "credentialsJSON:f5457b61-0c9d-4af0-a588-f4f760415094", display = ParameterDisplay.HIDDEN)
        }
        add {
            text("env.ASPNETCORE_ENVIRONMENT", "Production", readOnly = true, allowEmpty = true)
        }
    }

    expectSteps {
        exec {
            path = "build.sh"
            arguments = "Up --skip"
        }
    }
    steps {
        insert(0) {
            step {
                name = "Production docker-compose configuration"
                type = "MRPP_CreateTextFile"
                executionMode = BuildStep.ExecutionMode.DEFAULT
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/docker-compose.override.yml")
                param("content", """
                    version: '3.8'
                    
                    services:
                      host:
                        volumes:
                          - /keys:/keys
                        environment:
                          - ASPNETCORE_ENVIRONMENT=%env.ASPNETCORE_ENVIRONMENT%
                """.trimIndent())
            }
        }
        insert(1) {
            step {
                name = "Production database settings"
                type = "MRPP_CreateTextFile"
                executionMode = BuildStep.ExecutionMode.DEFAULT
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/Server/dbsettings.Production.json")
                param("content", """
                    {
                        "ConnectionStrings": {
                            "BlogConnectionString": "%env.POSTGRES_CONNECTION_STRING%"
                        }
                    }
                """.trimIndent())
            }
        }
        insert(2) {
            step {
                name = "Production application settings"
                type = "MRPP_CreateTextFile"
                executionMode = BuildStep.ExecutionMode.DEFAULT
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/Server/appsettings.Production.json")
                param("content", """
                    {
                      "Logging": {
                        "LogLevel": {
                          "Default": "Information",
                          "Microsoft": "Warning",
                          "Microsoft.Hosting.Lifetime": "Information"
                        }
                      },
                      "IdentityServer": {
                        "Key": {
                          "Type": "Development"
                        }
                      }
                    }
                """.trimIndent())
            }
        }
        insert(3) {
            step {
                name = "Production sentry settings"
                type = "MRPP_CreateTextFile"
                executionMode = BuildStep.ExecutionMode.DEFAULT
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/Server/sentrysettings.Production.json")
                param("content", """
                    {
                        "Sentry": {
                            "Dsn": "%env.SENTRY_DSN%"
                        }
                    }
                """.trimIndent())
            }
        }
        insert(4) {
            step {
                name = "Production jwt configuration"
                type = "CreateTextFile"
                executionMode = BuildStep.ExecutionMode.DEFAULT
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/Server/jwt.Production.json")
                param("content", """
                    {
                        "Jwt": {
                            "SecretKey": "%env.JWT_SECRET_KEY%"
                        }
                    }
                """.trimIndent())
            }
        }
        update<ExecBuildStep>(5) {
            clearConditions()
        }
    }
}
