version: '3.8'

x-restart-policy: &restart_policy
  restart: unless-stopped

x-host-config: &host_config
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
  ports:
    - "5003:80"

services:
  host:
    << : *restart_policy
    << : *host_config
    container_name: vl_blog_host
    image: vl_blog/host:latest
    build:
      context: .
      dockerfile: Server/Dockerfile
    volumes:
      - /D/Keys/blog:/keys