version: '3.7'

x-restart-policy: &restart_policy
  restart: unless-stopped

x-host-config: &host_config
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
  ports:
    - "5003:80"

services:
  host:
    << : *restart_policy
    << : *host_config
    depends_on:
      - postgres
    container_name: vl_blog_host
    image: vl_blog/host:latest
    build:
      context: .
      dockerfile: Server/Dockerfile
    networks:
      - host_network

  postgres:
    << : *restart_policy
    container_name: vl_blog_postgres
    image: postgres:12.4
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vl_blog
      - POSTGRES_PASSWORD=HYMLWXaUpZ6hVUaEQy
    command: ["-c", "shared_buffers=512MB", "-c", "max_connections=500"]
    volumes:
      - host_volume:/var/lib/postgresql/data
    networks:
      - host_network

volumes:
  host_volume:
    name: vl_blog_postgres_volume

networks:
  host_network:
    name: vl_blog_network